name: ud_mobile_app
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  # DI (Get It)
  get_it: ^7.6.0
  injectable: ^2.1.2

  # BLoC
  flutter_bloc: ^8.1.5
  bloc: ^8.1.2
  bloc_concurrency: ^0.2.2

  # Remote
  dio: ^5.4.3+1
  pretty_dio_logger: ^1.3.1
  json_annotation: ^4.9.0
  cached_network_image:
    ^3.3.1

    # Generated
  freezed_annotation: ^2.4.1
  freezed: ^2.5.2

  # Navigation Components
  auto_route:
    ^7.8.4

    # Local DB
  # flutter_secure_storage: ^4.2.1

  permission_handler: ^11.0.1
  # yandex_mapkit: ^4.1.0
  # geolocator: ^13.0.1

  # UI Style package
  flutter_svg: ^2.0.10+1
  # flutter_gen: ^5.3.2
  cupertino_icons: ^1.0.8
  # pin_code_fields: ^8.0.1
  mask_text_input_formatter: ^2.8.0
  # flutter_chat_ui: ^1.6.15
  dropdown_button2:
    ^2.3.9

    # Utils
  image_picker: ^1.0.7
  uuid: ^4.5.1
  file_picker: ^8.1.3
  mime: ^1.0.6
  flutter_localization: ^0.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  injectable_generator: ^2.4.1
  auto_route_generator: ^7.3.2
  flutter_gen_runner:

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/svg/
    - assets/image/
    - assets/lottie/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/RobotoRomanBlack.ttf
          # weight: 600
        - asset: assets/fonts/RobotoRomanMedium.ttf
          # weight: 200
        - asset: assets/fonts/RobotoRomanRegular.ttf
          # weight: 300
